# Generated by Django 4.0.3 on 2022-03-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
