# Generated by Django 4.0.3 on 2022-03-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
