# Generated by Django 4.0.3 on 2022-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
        ('main', '0006_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='participants',
            field=models.ManyToManyField(to='accounts.profile'),
        ),
    ]
