# Generated by Django 4.0.3 on 2022-03-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_studybook_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='owner',
            new_name='owners',
        ),
    ]
